tfxor/terrahub

- src/config-loader.js
- src/helpers/terrahub.js
**Test Configuration**:
* Firmware version: v0.0.18
> #THUB Fix terrahub run from anywhere

- src/commands/apply.js
- src/commands/destroy.js
- src/commands/run.js
> implement `auto-approve` option for `apply`, `destroy` and `run` commands

- src/commands/apply.js
- src/commands/build.js
- src/commands/destroy.js
- src/commands/run.js
- src/helpers/build-helper.js
Fixes # 215
**Test Configuration**:
* Hardware:
* Toolchain:
* SDK:
> Build new test environment

- src/commands/list.js
Fixes #142 
Command has been update to correspond lambda-authorizer requirement
> update `thub list` command to work with lambda-authorizer

- src/commands/run.js
- src/helpers/build-helper.js
- `thub run` without `apply` or `destroy` options requires no more confirmation
- `thub build --format json` command fixed to correspond `terraform external data` requirements
> minor improvement

- src/commands/list.js
Update `terrahub list` command to correspond new lambda response format
> update `terrahub list` command to correspond new lambda response format

- src/commands/apply.js
- src/commands/build.js
- src/commands/destroy.js
- src/commands/init.js
- src/commands/plan.js
- src/commands/run.js
- src/commands/workspace.js
- src/helpers/distributor.js
- src/terraform-command.js
Fixes #182 
- Remove dependencies validation for all commands except `apply` and `destroy`
- Reverse components' order for `destroy` action
> dependencies validation and order improved

- src/abstract-command.js
- src/commands/workspace.js
- src/config-loader.js
> implement `include` and `exclude` options functionality for `workspace` command

- src/helpers/distributor.js
- src/terraform-command.js
Fixes #280 
- improve behaviour for dependencies on non-existing components
> fix terraform commands not to finish after an error occurs

- src/helpers/build-helper.js
> change pwd for `build` command to config directory

- .codeclimate.json
- src/helpers/build-helper.js
- src/helpers/distributor.js
- src/helpers/terraform.js
- src/helpers/terrahub.js
- src/helpers/util.js
- src/helpers/worker.js
Implemented `.sh` language support.
P.S. Any other language should be implemented by devs, who knows the language.
> #THUB Improve hooks to support bash executable

- src/helpers/terraform.js
>  skip 'workspace select' if workspace is already selected

- src/commands/apply.js
- src/commands/build.js
- src/commands/destroy.js
- src/commands/init.js
- src/commands/plan.js
- src/commands/run.js
- src/commands/workspace.js
- src/helpers/terraform.js
- src/templates/help/metadata.json
- src/terraform-command.js
> add silent `option` for all terraform commands except output

- .eslintrc.json
* Hardware:
* Toolchain:
* SDK:
> Build new Test release

- src/commands/run.js
- src/helpers/distributor.js
- src/helpers/terraform.js
implement skip status for run -a
Fixes #227
> implement skip status for run -a

- .eslintrc.json
- package.json
- src/commands/run.js
- src/helpers/distributor.js
- src/helpers/terraform.js
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Build Test Environment with updates for terrahub version

- .codeclimate.json
- src/commands/refresh.js
- src/helpers/terraform.js
- src/templates/help/metadata.json
> Add `terrahub refresh` command

- src/templates/help/metadata.json
- src/terraform-command.js
add possibility to use regex with include/exclude commands
Fixes #315
> add possibility to use regex with include/exclude commands

- src/commands/apply.js
- src/commands/run.js
- src/helpers/distributor.js
- src/helpers/terraform.js
implement terrahub plan to be used for terrahub apply command
Fixes #320
> implement terrahub plan to be used for terrahub apply command

- .codeclimate.json
- package.json
- src/commands/apply.js
- src/commands/refresh.js
- src/commands/run.js
- src/helpers/distributor.js
- src/helpers/terraform.js
- src/templates/help/metadata.json
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Build Test Environment

- src/config-loader.js
- src/helpers/build-helper.js
- src/templates/config/component/.terrahub.yml.twig
- src/templates/config/project/.terrahub.yml.twig
- src/templates/help/metadata.json
- src/terraform-command.js
Fixes #294
1. Create a `terrahub` project
2. Initialise a `git` repository
3. Test different cases of components' and project's `ci mapping` configurations
> Add `git-diff` option to `terrahub run` command

- src/commands/plan.js
- src/helpers/distributor.js
- src/helpers/terraform.js
- src/templates/help/metadata.json
implement `--destroy` option for `terrahub plan` command
Fixes #322 
- run command `thub plan --destroy`
get next result on realtime page:
> implement --destroy option for terrahub plan command

- src/terraform-command.js
Fixes Bug with using `git-diff` option
> fix `git-diff` option

- src/commands/apply.js
- src/commands/build.js
- src/commands/destroy.js
- src/commands/init.js
- src/commands/output.js
- src/commands/plan.js
- src/commands/refresh.js
- src/commands/run.js
- src/commands/workspace.js
- src/helpers/distributor.js
- src/helpers/terraform.js
implement terrahub plan functionallity for terrahub run command with apply and destroy options, and destroy command
Fixes #323 #321
> implement terrahub plan functionallity for terrahub run command with apply and destroy options, and destroy command

- src/templates/aws/lambda_function/scripts/compare.sh
- src/templates/aws/lambda_function/scripts/download.sh
- src/templates/aws/lambda_function/scripts/shasum.sh
- src/templates/aws/lambda_function/scripts/upload.sh
- src/templates/aws/lambda_function/scripts/zip.sh
- src/templates/aws/s3_website/scripts/compare.sh
- src/templates/aws/s3_website/scripts/download.sh
- src/templates/aws/s3_website/scripts/shasum.sh
- src/templates/aws/s3_website/scripts/upload.sh
- src/templates/help/metadata.json
Fixes #323, #322, #321, #320, #286
* Hardware:
* Toolchain:
* SDK:
> Build new testing release

- src/helpers/distributor.js
- src/helpers/terraform.js
- src/helpers/util.js
- src/parameters.js
- src/templates/config/.terrahub.json
> add exponential backoff for `terraform init` action

- src/helpers/terraform.js
- src/helpers/terrahub.js
Fixes # https://github.com/TerraHubCorp/terrahub/issues/339
> add parse plan attributes to add/change/destroy

- src/helpers/terraform.js
- src/helpers/util.js
Fixes exponential backoff always working independently of condition for `terraform init` action
> fix exponential backoff for `terraform init` action

- src/commands/workspace.js
- src/templates/help/metadata.json
Change alias for `delete` option for `workspace` command from `d` to `D`
> change alias for `delete` option for `workspace` command from `d` to `D`

- src/templates/google/service_account/README.md.twig
- src/templates/google/service_account/main.tf.twig
- src/templates/google/service_account/variables.tf
- src/templates/google/service_account_key/README.md.twig
- src/templates/google/service_account_key/main.tf.twig
- src/templates/google/service_account_key/variables.tf
Fixes Google Cloud templates
- terrahub component -t google_project
* Hardware:
* Toolchain:
* SDK:
> Google template

- src/abstract-command.js
- src/config-loader.js
- src/templates/config/project/.terrahub.json.twig
- src/templates/config/project/.terrahub.yml.twig
improve terrahub speed
Fixes #333 
- `terrahub init`
> improve terrahub speed

- src/abstract-command.js
- src/commands/component.js
- src/commands/workspace.js
- src/config-loader.js
- src/templates/help/metadata.json
Add component delete command
Fixes #363
> add delete command to component

- src/templates/aws/efs_mount_target/README.md.twig
- src/templates/aws/iam_group/README.md.twig
- src/templates/aws/lambda_function/data.tf.twig
- src/templates/aws/lambda_function/default.tfvars.twig
- src/templates/aws/lambda_function/main.tf.twig
- src/templates/aws/lambda_function/scripts/compare.sh
Fix lambda template
* Hardware:
* Toolchain:
* SDK:
> fix lambda template

- src/helpers/terraform.js
- src/helpers/util.js
> handle more errors with exponential backoff

- src/commands/run.js
- src/templates/help/metadata.json
Adds `dry-run` option for the `terrahub run` command that prints out the list of the components that would be included in the run
> Add `dry-run` option to `terrahub run` command

- src/helpers/terrahub.js
Added possibility to run shell commands  
Fixes #341 
- `terrahub configure -c "hook.[command].[before/after]=mkdir arts"`
- `terrahub [command]`
- directory is successful created
> hooks fix and improvement

- src/helpers/terrahub.js
Fixes #341 
- `terrahub configure -c "hook.apply.before="./before.js"`
- run `terrahub plan`
see that terrahub doesn't crash anymore
> Hook fix with not specified command

- src/config-loader.js
- src/parameters.js
Fixes `terrahub` doesn't use environment
> Fix terrahub doesn't use environment

- src/helpers/terraform.js
Adds `exponential backoff` for `terraform plan` action.
Condition: `EOF` in the error message
> Add `exponential backoff` for `terraform plan` action

- src/commands/apply.js
- src/commands/destroy.js
- src/commands/run.js
- src/config-loader.js
- src/helpers/terrahub.js
- src/terraform-command.js
Fixes `terrahub` crashing when `hook` is not defined in the config
Improves error message for reverse dependency check
Bullets were replaced with row numbering
Tests were performed on the project with the following dependencies configuration
1: 3, 4
2: 3
3: 4
4: 1, 2
> Improve error message for reverse dependency check

- src/commands/apply.js
- src/commands/destroy.js
- src/commands/run.js
- src/helpers/distributor.js
- src/terraform-command.js
`forward`, `reverse` and `bidirectional` strings were replaced with the corresponding static number constants for performance improvement
> Replace raw strings with static number constants

- src/terraform-command.js
Fixes wrong value of static property BIDIRECTIONAL: changed from 0 to 2
> change value of BIDIRECTIONAL from 0 to 2

- src/commands/apply.js
- src/commands/destroy.js
- src/commands/run.js
- src/terraform-command.js
Fixes #397 
Project: [Project]
├─ [component1]
├─ [component2]
├─ [component3]
└─ [component4]
Project: [Project] | Components : [component1], [component2], [component3], [component4]
Do you want to perform apply action? (Y/N) n
Project: [Project] | Components : [component1], [component2], [component3], [component4]
Do you want to perform destroy action? (Y/N)
Project: [Project]
├─ [component1]
├─ [component2]
├─ [component3]
├─ [component4]
└─ [component5]
Do you want to perform apply action? (Y/N)
Project: [Project]
├─ [component1]
├─ [component2]
├─ [component3]
├─ [component4]
└─ [component5]
Do you want to perform destroy action? (Y/N)
* Hardware:
* Toolchain:
* SDK:
> Add dry-run before Question for apply/destroy/run

- src/commands/component.js
- src/config-loader.js
- src/parameters.js
- src/templates/config/component/.terrahub.json.twig
- src/templates/config/component/.terrahub.yml.twig
Fixes #337 #417
add specific template
run `terrahub component -n [name] -t [specific_template_name]`
> add codeblock in config-loader, combine component config with template specific config, fix project issue

- src/helpers/distributor.js
- src/helpers/util.js
- src/parameters.js
> add possibility to choose logical or physical threads

- docs/hooks.md
- package.json
- src/commands/component.js
- src/commands/project.js
- src/helpers/distributor.js
- src/helpers/terraform.js
- src/helpers/terrahub.js
- src/helpers/util.js
- src/parameters.js
- src/templates/aws/lambda_function/scripts/compare.sh
- src/templates/help/metadata.json
- src/terraform-command.js
Bug fixing related to dependency and improve terrahub component
* Hardware:
* Toolchain:
* SDK:
> Bug fixing related to dependency and improve terrahub component

- src/templates/config/.terrahub.json
Fixes #319 
Added console.log for visualization
- `"usePhysicalCpu": false`
- `"usePhysicalCpu": true`
* Hardware:
* Toolchain:
* SDK:
> add usePhysicalCpu to global config

- src/commands/component.js
Fixes #363 
Do you want to perform delete action? (Y/N) n
❌ Action aborted
Do you want to perform delete action? (Y/N) y
✅ Done
All .terrahub.* files were deleted from [name] component
> yesNoQuestion added for delete action for component

- index.js
- package.json
- src/helpers/terraform.js
Exports `getComponentBuildTask` function which allows to execute `build process` for one component
> Create index.js to export `terrahub` features

- src/commands/configure.js
> delete full chain if empty object

- src/commands/project.js
- src/config-loader.js
Fixes #376 
✅ Project successfully initialized
`terrahub project -n [name] -d [name]`
💡 Project already configured
> do not allow to create 2 projects in one folder

- src/commands/component.js
> Add possibility to create/delete multiple components

- src/commands/apply.js
- src/commands/destroy.js
- src/commands/init.js
- src/commands/output.js
- src/commands/plan.js
- src/commands/refresh.js
Fixes #326 
- run any terraform related command with `--env` and see 
[name]  Switched to workspace "[env]".
> add --env to all terraform related commands

- src/commands/project.js
>  directory path added

- src/helpers/terrahub.js
Add env variables in hooks inheritance
> add env variables inheritance in hooks

- src/helpers/terraform.js
Change List:
- add exponential backoff for `terraform` apply action
- merge `_checkIgnore` methods
> add exponential backoff for `terraform` apply action

- src/helpers/worker.js
> apply skip fix

- src/config-loader.js
- src/helpers/terrahub.js
Fixes #458 
Tested by console.log process.env in hook and in build
> add global env variables to hook/build

- src/terraform-command.js
Fixes `terrahub` crashes with `git-diff` option provided in case of component's dependencies missing in the run list
> Fix `git-diff` option crashes in case of dependencies missing in the run

- src/commands/apply.js
- src/commands/component.js
- src/commands/configure.js
- src/commands/destroy.js
- src/commands/output.js
- src/commands/run.js
- src/helpers/util.js
- src/templates/help/metadata.json
- src/terraform-command.js
> add delete for configure and component command, code improvement [WIP]

- src/commands/component.js
> add user-friendly error message

- src/commands/component.js
> fix for deleteComponent, code improvement

- src/commands/component.js
- src/commands/run.js
- src/templates/help/metadata.json
> add build step in terrahub run

- src/helpers/terrahub.js
Update terrahub cli to use new `parse-destroy` endpoint instead of `parse-state`
> Consolidate _callParseLambda w/ API

- src/helpers/terrahub.js
Remove redundant parameter thubAction from payload for `parse-*` lambda call
> Remove redundant parameter thubAction from payload

- src/commands/configure.js
- src/commands/output.js
- src/commands/refresh.js
- src/commands/run.js
- src/commands/workspace.js
- src/config-loader.js
- src/helpers/distributor.js
- src/helpers/terrahub.js
- src/helpers/util.js
- src/templates/config/project/.terrahub.json.twig
- src/templates/config/project/.terrahub.yml.twig
> Refactor distributed output handle

- src/commands/apply.js
- src/commands/destroy.js
- src/commands/run.js
- src/helpers/dictionary.js
- src/helpers/distributor.js
- src/helpers/terraform.js
- src/helpers/terrahub.js
- src/terraform-command.js
> Replace string action statuses with corresponding numbers

- src/helpers/terraform.js
* Hardware:
* Toolchain:
* SDK:
> Fix for `Worker Error`

- src/templates/aws/glue_catalog_database/README.md.twig
- src/templates/aws/glue_catalog_database/default.tfvars.twig
- src/templates/aws/glue_catalog_database/main.tf.twig
- src/templates/aws/glue_catalog_database/output.tf.twig
- src/templates/aws/glue_catalog_database/provider.tf
- src/templates/aws/glue_catalog_database/variables.tf
- src/templates/aws/glue_catalog_table/README.md.twig
- src/templates/aws/glue_catalog_table/default.tfvars.twig
- src/templates/aws/glue_catalog_table/main.tf.twig
- src/templates/aws/glue_catalog_table/output.tf.twig
- src/templates/aws/glue_catalog_table/provider.tf
- src/templates/aws/glue_catalog_table/variables.tf
- src/templates/aws/glue_connection/README.md.twig
- src/templates/aws/glue_connection/default.tfvars.twig
- src/templates/aws/glue_connection/main.tf.twig
- src/templates/aws/glue_connection/output.tf.twig
- src/templates/aws/glue_connection/provider.tf
- src/templates/aws/glue_connection/variables.tf
- src/templates/aws/glue_job/README.md.twig
- src/templates/aws/glue_job/default.tfvars.twig
- src/templates/aws/glue_job/main.tf.twig
- src/templates/aws/glue_job/output.tf.twig
- src/templates/aws/glue_job/provider.tf
- src/templates/aws/glue_job/variables.tf
- src/templates/mapping.json
- Added glue_catalog_database template
- Added glue_catalog_table template
- Added glue_connection template
- Added glue_job template
- terrahub run -y -a
* Hardware:
* Toolchain:
* SDK:
> Add new Glue templates

- src/helpers/terraform.js
> improved regular expressions

- src/helpers/terrahub.js
> Fix terrahub.js uses local constants instead of dictionary.js

- src/helpers/terraform.js
> Fix terrahub crashes when fails to fetch env vars from API

- package.json
- src/abstract-command.js
- src/commands/list.js
- src/config-loader.js
- src/helpers/downloader.js
- src/helpers/metadata.js
- src/helpers/terraform.js
- src/helpers/terrahub.js
- src/helpers/util.js
- src/helpers/worker.js
- src/parameters.js
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Building Test Environment with HotFix

- src/helpers/dictionary.js
- src/helpers/fetch.js
- src/helpers/terraform.js
Change list:
- consolidate realtime statuses dictionary with api
- add additional debug logs for http requests
> Consolidate realtime statuses dictionary with api

- package.json
- src/helpers/dictionary.js
- src/helpers/fetch.js
- src/helpers/terraform.js
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Build Stage Environment

- package.json
- src/helpers/dictionary.js
- src/helpers/fetch.js
- src/helpers/terraform.js
- src/templates/help/metadata.json
Hotfix for realtime data
* Hardware:
* Toolchain:
* SDK:
> Hotfix for realtime data

- src/helpers/terraform.js
- src/helpers/terrahub.js
- src/helpers/util.js
Change list:
- use exponentialBackoff for every terraform command
- add customizable intermediate action for exponentialBackoff function
- add message about exponential backoff retry
> Use exponentialBackoff for every terraform command

- src/commands/run.js
> Fix build step is executed after plan in case of no apply and no destroy

- package.json
- src/commands/run.js
- src/helpers/terraform.js
- src/helpers/terrahub.js
- src/helpers/util.js
- src/templates/help/metadata.json
Extend exponential backoff to all terraform related commands
* Hardware:
* Toolchain:
* SDK:
> Extend exponential backoff to all terraform related commands

- src/helpers/fetch.js
- src/helpers/terrahub.js
Handle status 500/504 from api response
> Handle status 500/504 from api response

- src/helpers/terrahub.js
> Fix error message in payload is empty in case of hook failure [WIP]

- src/helpers/terrahub.js
> Handle hook execution error

- package.json
- src/helpers/fetch.js
- src/helpers/terrahub.js
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Build Test Environment with lates code changes

- src/commands/apply.js
- src/commands/build.js
- src/commands/destroy.js
- src/commands/init.js
- src/commands/plan.js
- src/commands/refresh.js
- src/commands/run.js
- src/commands/workspace.js
- src/exceptions/list-exception.js
- src/helpers/terrahub.js
- src/helpers/util.js
- src/terraform-command.js
> List active resources in terrahub execution log

- src/helpers/distributor.js
- src/helpers/util.js
> Fix spawner error message is not a String

- src/commands/run.js
Fixes `terrahub run --dry-run` crashes
> Fix dry-run crash

- src/commands/run.js
* Hardware:
* Toolchain:
* SDK:
> Test Release

- src/templates/google/cloudfunctions_function/.terrahub.yml
- src/templates/google/cloudfunctions_function/scripts/build.sh
- src/templates/google/cloudfunctions_function/scripts/compare.sh
- src/templates/google/cloudfunctions_function/scripts/download.sh
- src/templates/google/cloudfunctions_function/scripts/shasum.sh
- src/templates/google/cloudfunctions_function/scripts/upload.sh
- src/templates/google/cloudfunctions_function/scripts/zip.sh
- Fixed Google Cloud Function Template
- terrahub run -a -y -i google_storage
- terrahub build -i google_function
- terrahub run -a -y
* Hardware:
* Toolchain:
* SDK:
> fix google cloud function template

- README.md
- docs/examples/README.md
- package.json
- src/commands/component.js
- src/helpers/terraform.js
- src/helpers/worker.js
- src/templates/config/project/.terrahub.yml.twig
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Stage Release

- README.md
- docs/examples/README.md
- package.json
- src/commands/component.js
- src/helpers/terraform.js
- src/helpers/worker.js
- src/templates/config/project/.terrahub.yml.twig
- src/templates/help/metadata.json
Fixes #611 #617
* Hardware:
* Toolchain:
* SDK:
> Bug fixes for terrahub component and terrahub worker

- src/helpers/logger.js
> Fix list-exception is printed with error stack ignoring debug level

- bin/cli.js
- src/terraform-command.js
- fixed issue 625
root@DESKTOP-ECSQPB1:/mnt/c/Terrahub/test-change-config# ls -al
total 0
drwxrwxrwx 1 euliancom euliancom 512 Mar 13 10:43 .
drwxrwxrwx 1 euliancom euliancom 512 Mar 13 10:43 ..
-rwxrwxrwx 1 euliancom euliancom 210 Mar 13 15:15 .terrahub.yml
root@DESKTOP-ECSQPB1:/mnt/c/Terrahub/test-change-config# cat .terrahub.yml
project:
name: test_project
code: b52d48e8
include:
- .
exclude:
- '**/.terraform/**'
- '**/node_modules/**'
- '**/.git/**'
terraform:
varFile:
- default.tfvars
version: 0.11.14
root@DESKTOP-ECSQPB1:/mnt/c/Terrahub/test-change-config# terrahub configure -c terraform.version=0.11.11
✅ Done
root@DESKTOP-ECSQPB1:/mnt/c/Terrahub/test-change-config# cat .terrahub.yml
project:
name: test_project
code: b52d48e8
include:
- .
exclude:
- '**/.terraform/**'
- …
> fixed issue 625

- src/helpers/util.js
Refactor util.js into static class and improve it
> Refactor util.js into class

- src/terraform-command.js
Add warn icon for execution started warning message
> Add warn icon for execution started warning message

- src/commands/run.js
- src/helpers/build-helper.js
Fix build step is executed after plan in case of `terrahub run --build --apply`
> Fix build step is executed after plan in case of run with apply

- docs/terrahub/homebrew.md
- docs/terrahub/launchpad.md
- package.json
- src/commands/run.js
- src/helpers/build-helper.js
- src/helpers/util.js
- src/templates/config/component/.terrahub.json.twig
- src/templates/config/component/.terrahub.yml.twig
- src/templates/help/metadata.json
- src/terraform-command.js
Fix terrahub run order of steps between build and plan
* Hardware:
* Toolchain:
* SDK:
> Fix terrahub run order of steps between build and plan

- src/commands/import.js
Fix wrong ThreadDistributor import path in ImportCommand
> Fix ThreadDistributor import issue

- src/commands/workspace.js
> Fix workspace command throws 'initialization required' error

- src/commands/workspace.js
> Fix workspace command execution tree title

- src/helpers/git-helper.js
- src/helpers/util.js
- src/parameters.js
- src/terraform-command.js
> Include components' dependencies in the execution list for git-diff

- src/helpers/util.js
- src/parameters.js
- src/templates/config/.terrahub.json
- src/terraform-command.js
> add listLimit parameter to global terrahub config

- src/commands/configure.js
- src/terraform-command.js
> add user-friendly message to `thub configure`

- src/commands/run.js
- src/helpers/distributors/cloud-distributor.js
- src/helpers/s3-helper.js
- src/helpers/util.js
> Refactor project upload to S3 step to upload only required files

- src/abstract-command.js
- src/commands/component.js
- src/commands/convert.js
- src/config-loader.js
> Fix default mapping to component's folder

- src/commands/init.js
- src/helpers/wrappers/terraform.js
- src/templates/help/metadata.json
- src/terraform-command.js
- fixed issue 642
```
...
Terraform detected that the backend type changed from "gcs" to "local".
[static_website]
[static_website] Successfully configured the backend "local"! Terraform will automatically
use this backend unless the backend configuration changes.
[static_website]
Initializing provider plugins...
[static_website]
[static_website] The following providers do not have any version constraints in configuration,
so the latest version was installed.
To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
[static_website] corresponding provider blocks in configuration, with the constraint strings
suggested below.
...
```
* Hardware:
* Toolchain:
* SDK:
> remove input

- package.json
- src/abstract-command.js
- src/commands/component.js
- src/commands/configure.js
- src/commands/convert.js
- src/commands/run.js
- src/config-loader.js
- src/helpers/distributors/cloud-distributor.js
- src/helpers/distributors/thread-distributor.js
- src/helpers/jit-helper.js
- src/helpers/s3-helper.js
- src/helpers/util.js
- src/helpers/wrappers/terraform.js
- src/parameters.js
- src/templates/config/.terrahub.json
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Stage Release with fix backend type, symlinks, default mapping, output list and refactor project upload step 

- package.json
- src/abstract-command.js
- src/commands/component.js
- src/commands/configure.js
- src/commands/convert.js
- src/commands/run.js
- src/config-loader.js
- src/helpers/distributors/cloud-distributor.js
- src/helpers/distributors/thread-distributor.js
- src/helpers/jit-helper.js
- src/helpers/s3-helper.js
- src/helpers/util.js
- src/helpers/wrappers/terraform.js
- src/parameters.js
- src/templates/config/.terrahub.json
- src/templates/help/metadata.json
- src/terraform-command.js
Introducing cloud distributor and improve terrahub commands messaging
* Hardware:
* Toolchain:
* SDK:
> Introducing cloud distributor and improve terrahub commands messaging

- src/commands/apply.js
- src/commands/destroy.js
- src/commands/run.js
- src/terraform-command.js
Refactor dependency cycle validation
```
MacBook-Pro-3:TerraformProjects maximchukitu$ thub project -n dependency -d dependency
✅ Project successfully initialized
MacBook-Pro-3:TerraformProjects maximchukitu$ cd dependency/
MacBook-Pro-3:dependency maximchukitu$ thub component -t aws_iam_role -n cmp_1 -o ../cmp_2
✅ Done
MacBook-Pro-3:dependency maximchukitu$ thub component -t aws_iam_role -n cmp_2 -o ../cmp_3
✅ Done
MacBook-Pro-3:dependency maximchukitu$ thub component -t aws_iam_role -n cmp_3 -o ../cmp_4
✅ Done
MacBook-Pro-3:dependency maximchukitu$ thub component -t aws_iam_role -n cmp_4 -o ../cmp_1
✅ Done
MacBook-Pro-3:dependency maximchukitu$ thub apply
❌ There is a dependency cycle between the following components: cmp_1, cmp_2, cmp_3, cmp_4
MacBook-Pro-3:dependency maximchukitu$ …
```
> Refactor dependency cycle validation

- src/config-loader.js
- src/exceptions/list-exception.js
- src/terraform-command.js
Refactor ListException to improve code quality
> Refactor ListException

- src/commands/component.js
Fixes #465
* Hardware:
* Toolchain:
* SDK:
> Add user friendly and informative message when trying to delete inexistent component

- src/helpers/jit-helper.js
- src/helpers/util.js
Fix project['path'] value is missing in locals.tf file
> Fix local.project['path'] value is not parsed

- src/helpers/distributors/cloud-distributor.js
- src/helpers/jit-helper.js
- src/helpers/metadata.js
- src/helpers/s3-helper.js
- src/helpers/wrappers/terraform.js
Fixes remote state status is not updated after `init` action
Remove redundant and unused methods
> Fix remote state initialization

- src/commands/graph.js
- src/helpers/wrappers/terraform.js
> terrahub graph command throws unhandled exception in non-project directory

- bin/publish.js
- src/commands/convert.js
- src/commands/destroy.js
- src/commands/list.js
- src/commands/run.js
- src/commands/workspace.js
- src/helpers/dictionary.js
- src/helpers/distributors/abstract-distributor.js
- src/helpers/util.js
- src/helpers/wrappers/terraform.js
> Resolve ESLint issues

- bin/publish.js
- package.json
- src/commands/convert.js
- src/commands/destroy.js
- src/commands/graph.js
- src/commands/list.js
- src/commands/run.js
- src/commands/workspace.js
- src/helpers/dictionary.js
- src/helpers/distributors/abstract-distributor.js
- src/helpers/distributors/cloud-distributor.js
- src/helpers/jit-helper.js
- src/helpers/metadata.js
- src/helpers/s3-helper.js
- src/helpers/util.js
- src/helpers/wrappers/terraform.js
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Stage Release with fixes for terrahub graph + convert improvements

- bin/publish.js
- package.json
- src/commands/convert.js
- src/commands/destroy.js
- src/commands/graph.js
- src/commands/list.js
- src/commands/run.js
- src/commands/workspace.js
- src/helpers/dictionary.js
- src/helpers/distributors/abstract-distributor.js
- src/helpers/distributors/cloud-distributor.js
- src/helpers/jit-helper.js
- src/helpers/metadata.js
- src/helpers/s3-helper.js
- src/helpers/util.js
- src/helpers/wrappers/terraform.js
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Production Release with terrahub graph + terrahub convert improvements

- src/commands/run.js
- src/commands/workspace.js
- src/config-loader.js
- src/helpers/build-helper.js
- src/helpers/distributors/worker.js
- src/helpers/util.js
- src/helpers/wrappers/terraform.js
Change list:
- fix dry run doesn't validate dependencies
- refactor BuildHelper
- fix workspace command doesn't print list header
- refactor ConfigLoader::_findRootConfig method from recursive to iterative
- fix terrahub crashes if 'include' is not defined in the project config
- minor code improvements
> Code refactoring and fixes of the last code refactoring

- src/commands/apply.js
- src/commands/build.js
- src/commands/component.js
- src/commands/destroy.js
- src/commands/import.js
- src/commands/init.js
- src/commands/plan.js
- src/commands/prepare.js
- src/commands/refresh.js
- src/commands/run.js
- src/commands/workspace.js
- src/config-loader.js
- src/helpers/build-helper.js
- src/helpers/distributors/abstract-distributor.js
- src/helpers/distributors/cloud-distributor.js
- src/helpers/distributors/thread-distributor.js
- src/helpers/wrappers/terraform.js
- src/templates/help/metadata.json
- src/terraform-command.js
Change List:
- remove 'silent' option as redundant
- consolidate ignore patterns
- fix incompatible override warning
> Remove silent option

- src/commands/component.js
- src/helpers/wrappers/terraform.js
…ment from workspace
Fixes #378
* Hardware:
* Toolchain:
* SDK:
> on create new component create terrahub config files for each environment

- src/helpers/jit-helper.js
> Fix tfvars auto type detection

- src/config-loader.js
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> fix dependency check on windows

- README.md
- docs/commands/README.md
- docs/examples/README.md
- docs/features/install.md
- docs/terrahub/README.md
* Hardware:
* Toolchain:
* SDK:
> Fix for thub run -u on windows and improvements for options

- src/config-loader.js
- src/helpers/wrappers/abstract-terrahub.js
- src/terraform-command.js
Fixes `terrahub` crashes in case of dependencies configured in the project
> Fix dependency validation

- src/config-loader.js
- src/helpers/wrappers/abstract-terrahub.js
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Test Release with fix for dependency validation

- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> improve dependency validation

- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Revert error commits

- src/config-loader.js
> Fix graph dependsOn 

- package.json
- src/commands/configure.js
- src/config-loader.js
- src/templates/google/project_default/.terrahub.yml.twig
- src/templates/google/project_default/scripts/apply.py
- src/templates/google/project_default_import/.terrahub.yml.twig
- src/templates/google/project_default_service_account/.terrahub.yml.twig
- src/templates/google/project_default_service_account/scripts/apply.py
- src/templates/google/project_default_service_account_add_role/.terrahub.yml.twig
- src/templates/google/project_default_service_account_add_role/scripts/apply.py
- src/templates/google/project_default_service_account_key/.terrahub.yml.twig
- src/templates/google/project_default_service_account_key/scripts/apply.py
- src/templates/google/project_default_service_enable/.terrahub.yml.twig
- src/templates/google/project_default_service_enable/scripts/apply.py
- src/templates/google/resource_manager_lien/.terrahub.yml.twig
- src/templates/help/metadata.json
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Test Release with fixes for graph dependencies

- package.json
- src/commands/configure.js
- src/config-loader.js
- src/templates/google/project_default/.terrahub.yml.twig
- src/templates/google/project_default/scripts/apply.py
- src/templates/google/project_default_import/.terrahub.yml.twig
- src/templates/google/project_default_service_account/.terrahub.yml.twig
- src/templates/google/project_default_service_account/scripts/apply.py
- src/templates/google/project_default_service_account_add_role/.terrahub.yml.twig
- src/templates/google/project_default_service_account_add_role/scripts/apply.py
- src/templates/google/project_default_service_account_key/.terrahub.yml.twig
- src/templates/google/project_default_service_account_key/scripts/apply.py
- src/templates/google/project_default_service_enable/.terrahub.yml.twig
- src/templates/google/project_default_service_enable/scripts/apply.py
- src/templates/google/resource_manager_lien/.terrahub.yml.twig
- src/templates/help/metadata.json
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Stage Release with fixes for graph dependencies

- package.json
- src/commands/configure.js
- src/config-loader.js
- src/templates/google/project_default/.terrahub.yml.twig
- src/templates/google/project_default/scripts/apply.py
- src/templates/google/project_default_import/.terrahub.yml.twig
- src/templates/google/project_default_service_account/.terrahub.yml.twig
- src/templates/google/project_default_service_account/scripts/apply.py
- src/templates/google/project_default_service_account_add_role/.terrahub.yml.twig
- src/templates/google/project_default_service_account_add_role/scripts/apply.py
- src/templates/google/project_default_service_account_key/.terrahub.yml.twig
- src/templates/google/project_default_service_account_key/scripts/apply.py
- src/templates/google/project_default_service_enable/.terrahub.yml.twig
- src/templates/google/project_default_service_enable/scripts/apply.py
- src/templates/google/resource_manager_lien/.terrahub.yml.twig
- src/templates/help/metadata.json
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Production Release with fixes for graph dependencies

- src/terraform-command.js
> improve reverse dependency validation

- src/helpers/distributors/thread-distributor.js
- src/helpers/jit-helper.js
- save old variables
- terrahub run
* Hardware:
* Toolchain:
* SDK:
> Save old variables

- package.json
- src/commands/apply.js
- src/commands/build.js
- src/commands/configure.js
- src/commands/convert.js
- src/commands/destroy.js
- src/commands/import.js
- src/commands/init.js
- src/commands/output.js
- src/commands/plan.js
- src/commands/prepare.js
- src/commands/refresh.js
- src/commands/run.js
- src/commands/workspace.js
- src/helpers/dependency-strategy/absract-dependecy-strategy.js
- src/helpers/dependency-strategy/dependencies-auto.js
- src/helpers/dependency-strategy/dependencies-ignore.js
- src/helpers/dependency-strategy/dependencies-include.js
- src/helpers/gs-helper.js
- src/helpers/jit-helper.js
- src/helpers/wrappers/terraform.js
- src/templates/google/factory/.terrahub.yml.twig
- src/templates/google/factory/scripts/apply.py
- src/templates/google/project_default/.terrahub.yml.twig
- src/templates/help/metadata.json
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Test Release with fixes and improvements 

- package.json
- src/commands/apply.js
- src/commands/build.js
- src/commands/configure.js
- src/commands/convert.js
- src/commands/destroy.js
- src/commands/import.js
- src/commands/init.js
- src/commands/output.js
- src/commands/plan.js
- src/commands/prepare.js
- src/commands/refresh.js
- src/commands/run.js
- src/commands/workspace.js
- src/helpers/dependency-strategy/absract-dependecy-strategy.js
- src/helpers/dependency-strategy/dependencies-auto.js
- src/helpers/dependency-strategy/dependencies-ignore.js
- src/helpers/dependency-strategy/dependencies-include.js
- src/helpers/gs-helper.js
- src/helpers/jit-helper.js
- src/helpers/wrappers/terraform.js
- src/templates/google/factory/.terrahub.yml.twig
- src/templates/google/factory/scripts/apply.py
- src/templates/google/project_default/.terrahub.yml.twig
- src/templates/help/metadata.json
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Stage Release with fixes and improvements

- package.json
- src/commands/apply.js
- src/commands/build.js
- src/commands/configure.js
- src/commands/convert.js
- src/commands/destroy.js
- src/commands/import.js
- src/commands/init.js
- src/commands/output.js
- src/commands/plan.js
- src/commands/prepare.js
- src/commands/refresh.js
- src/commands/run.js
- src/commands/workspace.js
- src/helpers/dependency-strategy/absract-dependecy-strategy.js
- src/helpers/dependency-strategy/dependencies-auto.js
- src/helpers/dependency-strategy/dependencies-ignore.js
- src/helpers/dependency-strategy/dependencies-include.js
- src/helpers/gs-helper.js
- src/helpers/jit-helper.js
- src/helpers/wrappers/terraform.js
- src/templates/google/factory/.terrahub.yml.twig
- src/templates/google/factory/scripts/apply.py
- src/templates/google/project_default/.terrahub.yml.twig
- src/templates/help/metadata.json
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Production Release with fixes and improvements

- src/templates/google/factory/scripts/apply.py
- fixed factory python script
- terrahub run -a -y
* Hardware:
* Toolchain:
* SDK:
>  fixed factory python script

- src/commands/component.js
- src/config-loader.js
- src/helpers/util.js
- src/terraform-command.js
Fixes #729 
When in project are components with same name:
> add validation on same components names in project

- src/commands/list.js
- src/helpers/dependency-strategy/dependencies-include.js
> update get aws regions

- package.json
- src/commands/list.js
- src/helpers/dependency-strategy/dependencies-include.js
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Test Release with fix for terrahub list command

- package.json
- src/commands/component.js
- src/commands/list.js
- src/config-loader.js
- src/helpers/dependency-strategy/dependencies-include.js
- src/helpers/util.js
- src/templates/google/factory/scripts/apply.py
- src/templates/help/metadata.json
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Stage Release with fix for terrahub list and component validation

- package.json
- src/commands/component.js
- src/commands/list.js
- src/config-loader.js
- src/helpers/dependency-strategy/dependencies-include.js
- src/helpers/util.js
- src/templates/google/factory/scripts/apply.py
- src/templates/help/metadata.json
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Production Release with fix for component validation and terrahub list command

- src/abstract-command.js
- src/commands/.help.js
- src/commands/list.js
> Improve validation in terrahub list command

- package.json
- src/abstract-command.js
- src/commands/.help.js
- src/commands/list.js
- src/commands/run.js
- src/exceptions/authentication-exception.js
- src/helpers/dependency-strategy/dependencies-ignore.js
- src/helpers/fetch.js
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Stage Release with improvements for terrahub list and thub_token validation

- docs/examples/structure.md
- package.json
- src/helpers/jit-helper.js
- merged `tfvars` generated from the file with root `tfvars`
- added convert `tfvars` from `hcl` format to `json` format
- implemented issue #753 
- terrahub run
* Hardware:
* Toolchain:
* SDK:
> merged `tfvars` generated from the file with root `tfvars`

- src/helpers/jit-helper.js
- added new feature
```
...
template:
locals:
component:
local: /tmp/.terrahub/test
...
````
- terrahub run
```
root@DESKTOP-ECSQPB1:/mnt/c/Terrahub/terraform-aws-landing-zone# cat ~/.terrahub/cache/jit/landing_zone_pipeline_s3_bucket_eef16dcf/locals.tf
{
"locals": {
"component": {
"name": "landing_zone_pipeline_s3_bucket",
"path": "/mnt/c/Terrahub/terraform-aws-landing-zone/components/landing_zone_pipeline_s3_bucket",
"local": "/tmp/.terrahub/test",
"remote": "terraform/terraform-aws-landing-zone"
},
"timestamp": 1559570661965,
"project": {
"path": "/mnt/c/Terrahub/terraform-aws-landing-zone",
"name": "terraform-aws-landing-zone",
"code": "eef16dcf"
}
}
}
```
```
root@DESKTOP-ECSQPB1:/mnt/c/Terrahub/terraform-aws-landing-zone# cat …
```
> Added permission to change `component[local]` and `component[remote]` from root config

- src/templates/help/metadata.json
- src/terraform-command.js
- fixed shortcat dependency
- terrahub configure -i landing_zone_pipeline_s3_bucket -c terraform -D -y
* Hardware:
* Toolchain:
* SDK:
> fixed shortcat dependency

- docs/examples/structure.md
- package.json
- src/helpers/jit-helper.js
- src/templates/help/metadata.json
- src/terraform-command.js
* Hardware:
* Toolchain:
* SDK:
> Customize `local` and `remote` parameters for each component

- package.json
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Test Release with fix for dependencies 

- package.json
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Fix for dependencies validation

- package.json
- src/templates/help/metadata.json
* Hardware:
* Toolchain:
* SDK:
> Fix dependencies validation

- src/helpers/jit-helper.js
- src/helpers/wrappers/terraform.js
* Hardware:
* Toolchain:
* SDK:
> Fix issue with workspace select and apply

- src/helpers/jit-helper.js
- src/helpers/wrappers/terraform.js
* Hardware:
* Toolchain:
* SDK:
> Fix issue with workspace select and output for apply 

- bin/cli.js
- src/commands/import.js
- src/helpers/distributors/worker.js
- src/helpers/util.js
> fix output message in import action

- src/helpers/util.js
- src/helpers/wrappers/terraform.js
> fix import output message, updated 

- src/terraform-command.js
- fixed git-diff
```
root@DESKTOP-ECSQPB1:/mnt/c/Terrahub/terrahub-api# terrahub run -y -b -X "^(...*)" -e test -g test..dev
💡 THUB_TOKEN is not provided.
Project: TerraHub_API | Components: api_gateway_....
```
* Hardware:
* Toolchain:
* SDK:
> Fixed git-diff command

- src/helpers/jit-helper.js
- src/parameters.js
- added new feature for use tfvars value inside TF scripts
- moved hardcode value to parameter
```
template:
provider:
- aws:
region: '${var.region}'
allowed_account_ids:
- '${var.account_id}'
- aws:
alias: default
region: '${var.region}'
allowed_account_ids:
- '${var.account_id}'
tfvars:
tfstate_path: /tmp/.terrahub/tfstate_local/terraform-aws-landing-zone
region: us-east-1
account_id: xxxxxxxxxxxx
```
```
provider_alias = "aws.default"
landing_zone_organization_unit_name = "LandingZone"
```
```
component:
name: landing_zone_organization_unit
dependsOn:
- ../landing_zone_organization
template:
terraform:
backend:
local:
path: >-
${tfvar.terrahub["tfstate_path"]}/landing_zone_organization/terraform.tfstate
data:
terraform_remote_state:
landing_zone_organization:
backend: local
config: …
```
> New features

- bin/cli.js
- package.json
- src/commands/import.js
- src/commands/output.js
- src/helpers/distributors/worker.js
- src/helpers/fetch.js
- src/helpers/jit-helper.js
- src/helpers/util.js
- src/helpers/wrappers/terraform.js
- src/parameters.js
- src/templates/aws/cloudfront_distribution/.terrahub.yml.twig
- src/templates/aws/cloudfront_distribution/scripts/invalidate.js
- src/templates/help/metadata.json
- src/terraform-command.js
Fixing bugs related to terrahub import and terrahub configs like `tfvars` and `dependsOn`
> Fixing bugs related to terrahub import and terrahub configs like `tfvars` and `dependsOn`

- bin/cli.js
- src/abstract-command.js
- src/commands/apply.js
- src/commands/build.js
- src/commands/component.js
- src/commands/destroy.js
- src/commands/import.js
- src/commands/init.js
- src/commands/output.js
- src/commands/plan.js
- src/commands/prepare.js
- src/commands/refresh.js
- src/commands/run.js
- src/commands/workspace.js
- src/helpers/distributors/abstract-distributor.js
- src/helpers/distributors/cloud-distributor.js
- src/helpers/distributors/thread-distributor.js
- src/helpers/distributors/worker.js
- src/helpers/fetch.js
- src/helpers/log-helper.js
- src/helpers/logger.js
- src/helpers/util.js
- src/helpers/wrappers/abstract-terrahub.js
- src/helpers/wrappers/terrahub.js
- src/parameters.js
- src/terraform-command.js
> Logger handler & ES logging & api workflow logging

- src/helpers/jit-helper.js
- added new features to use multi-providers in terraform
- terrahub run
* Hardware:
* Toolchain:
* SDK:
> Use multi-providers

- src/helpers/jit-helper.js
- fixed promise
- terrahub run
* Hardware:
* Toolchain:
* SDK:
> fixed promise

- src/helpers/jit-helper.js
- fixed recursive mkdir
- terrahub init without `~/.terrahub`
* Hardware:
* Toolchain:
* SDK:
> fixed recursive mkdir

- src/helpers/api-helper.js
- src/helpers/distributors/thread-distributor.js
- src/helpers/logger.js
- src/helpers/wrappers/abstract-terrahub.js
> update LoggerWorker - message handling, thread count, ES batch count

- src/helpers/wrappers/abstract-terrahub.js
> add additional message to backoff condition

- src/helpers/distributors/thread-distributor.js
- src/helpers/util.js
- src/parameters.js
> Add threadLimit variable to global config

- bin/publish.js
- src/helpers/help-parser.js
- src/templates/aws/regions/scripts/update.sh
> update aws `regions.json` on publish

- src/commands/component.js
- src/commands/list.js
- src/helpers/help-parser.js
- src/parameters.js
> updated templates path to avoid `templates/templates`

- src/helpers/git-helper.js
- src/terraform-command.js
> update gitDiff - warn if no changes 

- bin/cli.js
- src/helpers/distributors/thread-distributor.js
- src/helpers/util.js
- src/helpers/wrappers/abstract-terrahub.js
> Fix exponentialBackoff error handling

- src/helpers/util.js
- src/helpers/wrappers/abstract-terrahub.js
> fix retrieve region for tfvarsAccount

- src/helpers/util.js
- src/helpers/wrappers/abstract-terrahub.js
> Building release to support terraform v0.12+

- src/helpers/distributors/thread-distributor.js
- src/helpers/fetch.js
- src/helpers/s3-helper.js
- src/helpers/wrappers/terraform.js
> fix token validation for cloud, tfvars & backend accounts

- src/helpers/fetch.js
> minor changes

- src/helpers/distributors/thread-distributor.js
- src/helpers/s3-helper.js
- src/helpers/wrappers/terraform.js
> New release to support terraform v0.12+

- src/commands/apply.js
- src/commands/destroy.js
- src/helpers/wrappers/abstract-terrahub.js
> Fix do not skip apply, destroy in terrahub apply, destroy commands

- src/commands/apply.js
- src/commands/destroy.js
- src/helpers/wrappers/terraform.js
Fixes #830 
* Hardware:
* Toolchain:
* SDK:
> Fix auto skip actions `apply`, `destroy` and `refresh`

- src/helpers/jit-helper.js
- src/helpers/wrappers/terraform.js
- src/templates/config/project/.terrahub.yml.twig
Fixes #859 - Check the value of local.terrahub if corresponding value of tfvars.terrahub is missing
* Hardware:
* Toolchain:
* SDK:
> Check the value of local.terrahub if corresponding value of tfvars.terrahub is missing

- src/config-loader.js
If in component `.terrahub.yml` config mapping is not defined, adds default `mapping: []`
> add component config `mapping` validation

- src/helpers/jit-helper.js
- fixed replace local value for multiple providers
```
resource "aws_network_acl" "landing_zone_network_acl" {
provider   = "aws.default"
count      = length(var.default_provider["landing_zone_network_acl_resource"])
vpc_id     = element(data.aws_vpc.vpc_selected.*.id, count.index)
tags       = local.elements_landing_zone_network_acl_tags_map["config_${count.index}"]
subnet_ids = slice(data.aws_subnet.subnet_selected.*.id, local.elements_landing_zone_network_acl_map["config_${count.index}"]["subnets_from_index"], local.elements_landing_zone_network_acl_map["config_${count.index}"]["subnets_to_index"])
}
```
```
resource "aws_network_acl" "landing_zone_network_acl_mitocgroup" {
provider   = "aws.mitocgroup"
count      = length(var.mitocgroup_provider["landing_zone_network_acl_resource"]) …
```
> fixed replace local value for multiple providers

- src/helpers/hcl-helper.js
> Fix deprecation warning

- package.json
- src/config-loader.js
- src/helpers/hcl-helper.js
- src/terraform-command.js
Fixes #860 
```yml
component:
name: test-4
dependsOn: [test-1, test-2, test-3, test-5, test-6]
template:
terraform:
backend:
s3:
key: terraform/ssm_parameter/4-tester/terraform.tfstate
bucket: data-lake-terrahub-us-east-1
region: us-east-1
resource:
aws_ssm_parameter:
lambda_deployer_test_parameter:
name: test-name-4
value: "${data.terraform_remote_state.my_prefix_test-6_0property_1property.outputs.text}, ${data.terraform_remote_state.my_prefix_test-5_0property_1property.outputs.text}, ${data.terraform_remote_state.test_3_0property.outputs.text}, ${data.terraform_remote_state.my_prefix_test-2_0property_1property.outputs.text}, ${data.terraform_remote_state.my_prefix_test-1_0property_1property.outputs.text}"
type: String
dynamic:
data:
terraform_remote_state:
- component: "*"
name: …
```
> Define `terraform_remote_state` from component dynamic.data object 

- src/helpers/util.js
Fixes #890
```
➜ terrahub configure --config component={}
💡 THUB_TOKEN is not provided.
❌ Configuration file not found. Either re-run the same command in project's root or initialize new project with `terrahub project`.
```
> return empty object instead of undefined when parse yaml(yml) file to JSON and is empty

- bin/cli.js
- src/terraform-command.js
> fix remote_state parse variables & DEBUG=debug option

- src/helpers/wrappers/terraform.js
- ignore errors on `import` command
- terrahub run
* Hardware:
* Toolchain:
* SDK:
> ignore errors on `import` command

- src/terraform-command.js
```yml
terraform:
backend:
gcs:
bucket: "gcs_bucket_name"
prefix: "gcs_prefix"
```
> Add dynamic `terraform_remote_state` for Google Cloud Storage

- src/commands/import.js
- Fixed regex for the import command
- terrahub import -b ....
* Hardware:
* Toolchain:
* SDK:
> Fix regex for the import command

- src/helpers/util.js
Fixes #911 
Tested on terrahub-api project:
> Fix graph command

- bin/converter/main.go
- src/helpers/hcl-helper.js
* Hardware:
* Toolchain:
* SDK:
> Update convertor and minor fix

- bin/publish.js
> Fix npm publish execution string

- bin/publish.js
> Fix publish syntax

- src/commands/run.js
* Hardware:
* Toolchain:
* SDK:
> Do not validate dependencies direction if `run` used without apply or destroy option

- src/commands/output.js
- src/helpers/distributors/distributor.js
> Fix output command

- src/commands/apply.js
> Fix apply command

- src/helpers/distributors/distributor.js
> fix workspace command

- src/commands/output.js
- src/helpers/distributors/worker.js
> Fix output command when is big amount of data

- src/helpers/util.js
- src/helpers/wrappers/terraform.js
If you want to have backend in one account and actually deploy in another account:
```yml
terraform:
cloudAccount: 'account where component will be deployed'
backendAccount: 'account where backend will be saved'
``` 
Otherwise if you want backend and deploy be in the same account use only `cloudAccount`:
```yml
terraform:
cloudAccount: 'terrahub'
```
> add roles in shared config for each account

- src/helpers/api-helper.js
- src/helpers/distributors/aws-cloud-deployer.js
Fixes ### Saving Lambda logs in terahub.console
> fix runId when send logs from lambda

- src/commands/import.js
- src/helpers/distributors/aws-cloud-deployer.js
- src/helpers/distributors/aws-distributor.js
- src/helpers/distributors/distributor.js
- setup project.distributor or component.distributor to `lambda`
- setup template.terraform.backend to `s3`
> distribute import in lambda

- src/distributed-command.js
- src/helpers/distributors/distributor.js
> Output command, parse ${tfvar.terrahub["component"]["name"]} when creating terraform_remote_state

- src/distributed-command.js
* Hardware:
* Toolchain:
* SDK:
> Minor fix for processRemoteStateTemplate function

- src/helpers/distributors/aws-cloud-deployer.js
- src/helpers/distributors/distributor.js
- src/helpers/wrappers/terraform.js
```yml
project:
name: terraform-aws-landing-zone
code: eef16dcf
distributor: lambda
include:
- .
exclude:
- .git
- node_modules
- '**/.backup'
- '**/.terraform'
terraform:
varFile:
- default.tfvars
version: 0.12.13
cloudAccount: aluchianic
template:
terraform:
backend:
s3:
bucket: terrahub-landing-zone-us-east-1-backend
key: terraform/aluchianic-import-batch/${tfvar.terrahub["component"]["name"]}/terraform.tfstate
region: us-east-1
provider:
- aws:
region: var.region
allowed_account_ids:
- var.account_id
- aws:
alias: default
region: var.region
allowed_account_ids:
- var.account_id
- aws:
alias: sample
region: var.sample_region
allowed_account_ids:
- var.sample_account_id
tfvars:
account_id: 0123456789012
region: us-east-1
sample_account_id: 0123456789012
sample_region: us-east-1
``` …
> Distributes config by component.targets block

- src/helpers/distributors/distributor.js
> exit from execution on error's with `[AWS distributor]`

- src/helpers/hcl-helper.js
- ignore `provider!`
- terrahub run
* Hardware:
* Toolchain:
* SDK:
> fixed outputs only for privider option

- src/helpers/hcl-helper.js
- minor improvements and bug fixes
- terrahub run
* Hardware:
* Toolchain:
* SDK:
> Minor improvements and bug fixes

- src/helpers/api-helper.js
* Hardware:
* Toolchain:
* SDK:
> Add 'import' command as workflow use case

- src/helpers/api-helper.js
* Hardware:
* Toolchain:
* SDK:
> Hotfix for API endpoint URL

- .codeclimate.json
- .eslintrc.json
- package.json
- src/commands/import.js
- src/commands/state.js
- src/config-loader.js
- src/distributed-command.js
- src/helpers/api-helper.js
- src/helpers/metadata.js
- src/helpers/prepare-helper.js
- src/helpers/wrappers/abstract-terrahub.js
- src/helpers/wrappers/terraform.js
- src/helpers/wrappers/terrahub.js
* Hardware:
* Toolchain:
* SDK:
> Update the engine versions, fix ESLint issues and codebase updates 

- src/helpers/wrappers/terrahub.js
* Hardware:
* Toolchain:
* SDK:
> Use Promise.all instead of Promise.allSettled

- .gitignore
- src/exceptions/not-found-exception.js
- src/helpers/fetch.js
- src/helpers/wrappers/abstract-terrahub.js
- src/helpers/wrappers/terrahub.js
* Hardware:
* Toolchain:
* SDK:
> Fix TerraHub realtime process and improve its performance

- src/helpers/wrappers/terrahub.js
* Hardware:
* Toolchain:
* SDK:
> Check if THUB_TOKEN is present

- .codeclimate.json
- .eslintrc.json
- .gitignore
- package.json
- src/commands/import.js
- src/commands/state.js
- src/config-loader.js
- src/distributed-command.js
- src/exceptions/not-found-exception.js
- src/helpers/api-helper.js
- src/helpers/fetch.js
- src/helpers/metadata.js
- src/helpers/prepare-helper.js
- src/helpers/wrappers/abstract-terrahub.js
- src/helpers/wrappers/terraform.js
- src/helpers/wrappers/terrahub.js
- src/templates/help/metadata.json
* Added better error handling for HTTP 404 responses
* Fixed bug related to terrahub component create
* Fixed bug related to realtime signals management
> Fixing bugs related to terrahub components and realtime signals

- bin/converter/main.go
* Hardware:
* Toolchain:
* SDK:
> Update converter and its binaries

- bin/cli.js
- package.json
- src/commands/output.js
- src/helpers/distributors/distributor.js
- src/helpers/distributors/websocket.js
- src/helpers/util.js
Fixes `process.exit` issues
* Hardware:
* Toolchain:
* SDK:
> Let Nodejs exit with success when the I/O is flushed and other processes are done

- src/commands/component.js
Fixes #988
* Hardware:
* Toolchain:
* SDK:
> Fix issue #988

- src/templates/aws/lambda_function/scripts/compare.sh
- src/templates/aws/lambda_function/scripts/compile.sh
- src/templates/aws/lambda_function/scripts/download.sh
- src/templates/aws/lambda_function/scripts/shasum.sh
- src/templates/aws/lambda_function/scripts/upload.sh
- src/templates/aws/lambda_function/scripts/zip.sh
Fixes Lambda function shell scripts
* Hardware:
* Toolchain:
* SDK:
> Update Lambda function shell scripts

- src/config-loader.js
- src/templates/aws/lambda_function/.terrahub.yml.twig
- src/templates/aws/lambda_function/scripts/compare.sh
- src/templates/aws/lambda_function/scripts/compile.sh
- src/templates/aws/lambda_function/scripts/download.sh
- src/templates/aws/lambda_function/scripts/shasum.sh
- src/templates/aws/lambda_function/scripts/upload.sh
- src/templates/aws/lambda_function/scripts/zip.sh
Minor improvements to Lambda Function template
* Hardware:
* Toolchain:
* SDK:
> Minor improvements to Lambda Function template

- src/helpers/wrappers/abstract-terrahub.js
* Hardware:
* Toolchain:
* SDK:
> Update errors for retry

- src/helpers/wrappers/abstract-terrahub.js
Fixed issue related to exponential backoff on `ECONNRESET` message
> Building new production release

- .gitignore
- src/distributed-command.js
- src/helpers/util.js
* Hardware:
* Toolchain:
* SDK:
> Do not include deps in git-diff. Fix cloud accounts

- .gitignore
- SECURITY.md
- bin/cli.js
- package.json
- src/distributed-command.js
- src/helpers/distributors/aws-cloud-deployer.js
- src/helpers/distributors/aws-distributor.js
- src/helpers/distributors/distributor.js
- src/helpers/s3-helper.js
- src/helpers/util.js
- src/templates/help/metadata.json
Fixed bugs related to cloudAccount, backendAccount and LAMBDA distributor
> Building new beta version

- .gitignore
- SECURITY.md
- bin/cli.js
- package.json
- src/distributed-command.js
- src/helpers/distributors/aws-cloud-deployer.js
- src/helpers/distributors/aws-distributor.js
- src/helpers/distributors/distributor.js
- src/helpers/s3-helper.js
- src/helpers/util.js
- src/templates/help/metadata.json
- src/templates/help/regions.aws.json
Fixed bugs related to cloudAccount, backendAccount and LAMBDA distributor
> Building new release candidate

- .gitignore
- SECURITY.md
- bin/cli.js
- package.json
- src/distributed-command.js
- src/helpers/distributors/aws-cloud-deployer.js
- src/helpers/distributors/aws-distributor.js
- src/helpers/distributors/distributor.js
- src/helpers/s3-helper.js
- src/helpers/util.js
- src/templates/help/metadata.json
- src/templates/help/regions.aws.json
Fixed bugs related to cloudAccount, backendAccount and LAMBDA distributor
* Hardware:
* Toolchain:
* SDK:
> Fixed bugs related to cloudAccount, backendAccount and LAMBDA distributor

- src/abstract-command.js
- src/helpers/distributors/distributor.js
- src/helpers/s3-helper.js
Fixed issue related to WebSockets API
* Hardware:
* Toolchain:
* SDK:
> Fixed issue related to WebSockets API

- .codeclimate.json
- bin/cli.js
- src/abstract-command.js
- src/commands/component.js
- src/config-loader.js
- src/distributed-command.js
- src/helpers/distributors/distributor.js
- src/helpers/downloader.js
- src/helpers/fetch.js
- src/helpers/prepare-helper.js
- src/helpers/util.js
- src/helpers/wrappers/abstract-terrahub.js
- src/helpers/wrappers/terraform.js
> Configure backendConfig and cloudConfig (similar to backendAccount and cloudAccount)

- .codeclimate.json
- bin/cli.js
- package.json
- src/abstract-command.js
- src/commands/component.js
- src/config-loader.js
- src/distributed-command.js
- src/helpers/distributors/distributor.js
- src/helpers/downloader.js
- src/helpers/fetch.js
- src/helpers/prepare-helper.js
- src/helpers/util.js
- src/helpers/wrappers/abstract-terrahub.js
- src/helpers/wrappers/terraform.js
- src/templates/help/metadata.json
Fixed cloud config and backend config variables
* Hardware:
* Toolchain:
* SDK:
> Fixed cloud config and backend config variables

- src/distributed-command.js
- src/helpers/distributors/distributor.js
- src/helpers/wrappers/terraform.js
> Fix env_vars for project/component

- src/distributed-command.js
- src/helpers/distributors/distributor.js
- src/helpers/wrappers/terraform.js
Fixed passing environment variables to each distributor
* Hardware:
* Toolchain:
* SDK:
> Fixed passing environment variables to each distributor

- .codeclimate.json
- src/helpers/util.js
- src/helpers/wrappers/terraform.js
Fixed explicit provider definition (default: aws)
* Hardware:
* Toolchain:
* SDK:
> Fixed explicit provider definition (default: aws)

- src/helpers/distributors/aws-cloud-deployer.js
- src/helpers/distributors/distributor.js
- src/helpers/downloader.js
- src/helpers/prepare-helper.js
- src/helpers/wrappers/sentinel.js
- src/helpers/wrappers/terraform.js
Fixed `Text file busy` error
* Hardware:
* Toolchain:
* SDK:
> Fixed `Text file busy` error

- .codeclimate.json
- src/helpers/hcl-helper.js
Fixed absolute path for modules in template definitions
* Hardware:
* Toolchain:
* SDK:
> Fixed absolute path for modules in template definitions

- src/helpers/distributors/worker.js
Fix Issue Related to Missing Remote State
> Fix Issue Related to Missing Remote State

- src/config-loader.js
- src/templates/config/component/.terrahub.null.json.twig
- src/templates/config/component/.terrahub.null.yml.twig
- added abstract `.terrahub.yml`
- tested on local machine
* Hardware:
* Toolchain:
* SDK:
> Feature/abstract `.terrahub.yml`

- src/config-loader.js
- src/templates/config/component/.terrahub.null.json.twig
- src/templates/config/component/.terrahub.null.yml.twig
- src/templates/config/project/.terrahub.all.json.twig
- src/templates/config/project/.terrahub.all.yml.twig
- added abstract `.terrahub.yml`
- tested on local machine
* Hardware:
* Toolchain:
* SDK:
> Feature/added abstract `.terrahub.yml`

- README.md
- SECURITY.md
- docs/CONTRIBUTING.md
- docs/README.md
- docs/automation/README.md
- docs/examples/README.md
- docs/terrahub/README.md
- docs/terrahub/homebrew.md
- package.json
- src/config-loader.js
- src/helpers/fetch.js
- src/templates/config/project/.terrahub.all.json.twig
- src/templates/config/project/.terrahub.all.yml.twig
Create generic project configuration when .terrahub.yml (or json) is missing
> Create generic project configuration when .terrahub.yml (or json) is missing

- src/config-loader.js
- fixed problem with component folder
```
cd terraform
terrahub run -i lambda_layer_lib_tfxor,lambda_layer_lib_tfxor_models,lambda_layer_lib_tfxor_models_helper,lambda_component_post,api_gateway_rest_api,api_gateway_deployment -b -p ignore
```
* Hardware:
* Toolchain:
* SDK:
> Fix/No components defined in configuration file.

- src/config-loader.js
Fix issue related to `no components defined in configuration file`
> Fix issue related to `no components defined in configuration file`

- src/helpers/wrappers/abstract-terrahub.js
Added more exponential backoff messages to resolve the following issues:
* https://github.com/tfxor/terrahub/issues/1061#issuecomment-777901430
* https://github.com/tfxor/terrahub/issues/1061#issuecomment-777902996
* https://github.com/tfxor/terrahub/issues/1061#issuecomment-777903508
* https://github.com/tfxor/terrahub/issues/1061#issuecomment-778170046
> added more exponential backoff messages

- src/helpers/hcl-helper.js
- Enhance environment variables THUB_VAR_xyz #1078 
- tested an localhost
* Hardware:
* Toolchain:
* SDK:
> Enhance environment variables THUB_VAR_xyz

- bin/publish.js
- package.json
- src/helpers/distributors/aws-distributor.js
- src/helpers/hcl-helper.js
- src/helpers/s3-helper.js
- src/helpers/util.js
- src/helpers/wrappers/terrahub.js
- src/templates/help/metadata.json
Refactoring TerraHub API endpoints for TerraHub CLI interactions
> Refactoring TerraHub API endpoints for TerraHub CLI interactions

- lib/scripts/aws/cloudfront_distribution/build.sh
- lib/scripts/aws/cloudfront_distribution/invalidate.sh
- lib/scripts/aws/lambda_function/build.sh
- lib/scripts/aws/lambda_function/compare.sh
- lib/scripts/aws/lambda_function/compile.sh
- lib/scripts/aws/lambda_function/download.sh
- lib/scripts/aws/lambda_function/shasum.sh
- lib/scripts/aws/lambda_function/upload.sh
- lib/scripts/aws/lambda_function/zip.sh
- lib/scripts/aws/s3_bucket/build.sh
- lib/scripts/aws/s3_bucket/compare.sh
- lib/scripts/aws/s3_bucket/compile.sh
- lib/scripts/aws/s3_bucket/download.sh
- lib/scripts/aws/s3_bucket/shasum.sh
- lib/scripts/aws/s3_bucket/upload.sh
> bugfix for bash

- lib/scripts/aws/cloudfront_distribution/build.sh
- lib/scripts/aws/cloudfront_distribution/invalidate.sh
- lib/scripts/aws/lambda_function/build.sh
- lib/scripts/aws/lambda_function/compare.sh
- lib/scripts/aws/lambda_function/compile.sh
- lib/scripts/aws/lambda_function/download.sh
- lib/scripts/aws/lambda_function/shasum.sh
- lib/scripts/aws/lambda_function/upload.sh
- lib/scripts/aws/lambda_function/zip.sh
- lib/scripts/aws/s3_bucket/build.sh
- lib/scripts/aws/s3_bucket/compare.sh
- lib/scripts/aws/s3_bucket/compile.sh
- lib/scripts/aws/s3_bucket/download.sh
- lib/scripts/aws/s3_bucket/shasum.sh
- lib/scripts/aws/s3_bucket/upload.sh
Fixed double brackets in shell
> Fixed double brackets in shell
